spring.application.name=receta-servicio
server.port=8087

spring.datasource.url=jdbc:mariadb://localhost:3306/veterinaria_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

logging.level.com.vidaysalud.veterinaria=INFO

servicios.consulta.url=http://localhost:8085/api/v1/consultas
servicios.medicamento.url=http://localhost:8086/api/v1/medicamentos
